### ISSUE TITLE
tried to complile... so many errors...

### ISSUE THREAD

**Issue by reddai75** [CybDis/Lilygo-T5-4.7-WeatherStation-with-HomeAssistant#5] opened 2024-10-31 00:13 UTC
Hey thank you for your project,
I have tried to compile it but I get so many errors...  I have installed the libraries, changed the configuration, made a subscriptio to owm... but when I compile it I get so many errors....
: In function 'uint8_t StartWiFi()':
 error: 'class WiFiClass' has no member named 'setAutoConnect'; did you mean 'setAutoReconnect'?
   96 |   WiFi.setAutoConnect(true);
 In function 'void drawString(int, int, String, alignment)':
error: invalid conversion from 'int*' to 'int32_t*' {aka 'long int*'} [-fpermissive]
 1024 |   get_text_bounds(&currentFont, data, &xx, &yy, &x1, &y1, &w, &h, NULL);
etc etc etc...
is there anyone willing to help ?

**Comment by CybDis** [comment] 2024-10-31 06:38
Hi,

the problem seems to be, that the ESP32 board manager has deprecated some methods. The code wasn't updated for some time. 
See this comment, for a temporary workaround:  
> https://forum.arduino.cc/t/error-with-wifi-hpp-when-compiling-painless-mesh-code/1248608/13

I'll see if I can update the deps and code sometime the next weeks.

**Comment by reddai75** [comment] 2024-10-31 08:19
Let me buy you a coffee

**Comment by CybDis** [comment] 2024-11-01 10:55
@reddai75 what development environment are you using?  
PlatformIO as recommended, or any other?

**Comment by CybDis** [comment] 2024-11-01 12:31
> @reddai75 what development environment are you using? PlatformIO as recommended, or any other?

I cannot reproduce any compile errors with PlatformIO. Clean and freshly cloned project, compiles just fine here:

```
Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (6.9.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20017.0 (2.0.17) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Converting OWM_EPD47.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 38 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Wire @ 2.0.0
|-- LilyGo-EPD47 @ 1.0.1+sha.2325b3a
|-- ArduinoJson @ 6.17.3
|-- PubSubClient @ 2.8.0
|-- HTTPClient @ 2.0.0
|-- SPI @ 2.0.0
|-- WiFi @ 2.0.0
Building in release mode
Compiling .pio\build\esp32dev\src\OWM_EPD47.ino.cpp.o
[...]
```

PlatformIO uses _framework-arduinoespressif32 @ 3.20017.0 **(2.0.17)** _ which is compatible with the code.  
Nevertheless, the `setAutoReconnect` is not necessary as the connection is implicit with a retry, so I've removed that line.

**Comment by yeckel** [comment] 2024-11-24 17:39
Hi, I run into the same issue, but with platformio:
`Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing https://github.com/tasmota/arduino-esp32/releases/download/3.0.4.240802/framework-arduinoespressif32.zip
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-arduinoespressif32@3.0.4+sha.0732d1b has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (2024.8.10) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.0.4+sha.0732d1b 
 - tool-esptoolpy @ 4.7.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
Converting OWM_EPD47.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Wire @ 3.0.4
|-- LilyGo-EPD47 @ 1.0.1+sha.bc51722
|-- ArduinoJson @ 6.17.3
|-- PubSubClient @ 2.8.0
|-- HTTPClient @ 3.0.4
|-- SPI @ 3.0.4
|-- WiFi @ 3.0.4
`

It seems to me that the framework-arduinoespressif32 and wifi has updated and broke the API. I was able to change the int(s) to int32_t, however there remains an issue with non-existent esp_spiffs.h included from LilyGo-EPD47/src/libjpeg/libjpeg.c

**Comment by yeckel** [comment] 2024-11-24 18:29
Ok, fixed in https://github.com/CybDis/Lilygo-T5-4.7-WeatherStation-with-HomeAssistant/pull/7

**Comment by CybDis** [comment] 2024-11-24 19:18
Merged

**Closed by CybDis** 2024-11-24 19:18 UTC
Labels: help wanted
